// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/farid141/go-rest-api/config"
	"github.com/farid141/go-rest-api/controller"
	"github.com/farid141/go-rest-api/db"
	"github.com/farid141/go-rest-api/repository"
	"github.com/farid141/go-rest-api/router"
	"github.com/farid141/go-rest-api/service"
)

// Injectors from wire.go:

func InitializeApp() (*AppContainer, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(sqlDB)
	userService := service.NewUserService(userRepository)
	authService := service.NewAuthService(userRepository)
	userController := controller.NewUserController(userService)
	authController := controller.NewAuthController(authService)
	routerRouter := router.NewRouter(userController, authController)
	appContainer := &AppContainer{
		UserService: userService,
		AuthService: authService,
		Router:      routerRouter,
	}
	return appContainer, nil
}

// wire.go:

type AppContainer struct {
	UserService service.UserService
	AuthService service.AuthService
	Router      *router.Router
}
